const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'assets/v318/intelligence.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/v318/intelligence.css'),'utf8');
const data=JSON.parse(fs.readFileSync(path.join(root,'data/v318/intelligence.json'),'utf8'));
const gaps=JSON.parse(fs.readFileSync(path.join(root,'data/v318/research_gaps.json'),'utf8'));
assert(html.includes('assets/v318/intelligence.js?v=3.18.0'));
assert(js.includes("data/v318/intelligence.json"));
assert(html.includes('id="tracePortal"')&&html.includes('id="helpPortal"'));
assert(css.includes('z-index:2147483000'));
assert(js.includes('repositionTracePortal(); repositionHelpPortal();'));
assert(!js.includes("document.addEventListener('pointerover'"));
assert(!js.includes("document.addEventListener('pointerout'"));
assert(js.includes("const trace=e.target.closest('.traceable')"));
assert(js.includes('window.jspdf?.jsPDF')&&js.includes('pdfAddExecutive'));
assert(!html.includes('btnIngest')&&!html.includes('btnContributions'));
const vendors=new Set(data.manufacturers.map(x=>x.name.toLowerCase()));
assert(!data.distributors.some(x=>vendors.has(x.name.toLowerCase())));
assert(data.distributors.length>=50&&data.integrators.length>=120&&data.clients_private.length===51&&data.clients_public.length>=25);
assert(gaps.version==='3.18.0'&&gaps.total_gaps>0&&gaps.total_gaps<2500&&gaps.coverage&&gaps.engine.passes_per_gap===48);
assert(js.includes('missingMarkup')&&js.includes('Por investigar</span>')&&!js.includes('>—<'));
assert(JSON.stringify(data.schemas.distributors).includes('Facturación / escala pública'));
console.log('UI smoke v3.18.0 · PASS');
