const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'assets/v370/intelligence.js'), 'utf8');
const data = JSON.parse(fs.readFileSync(path.join(root, 'data/v37/intelligence.json'), 'utf8'));
function assert(condition, message) { if (!condition) throw new Error(message); }
const views = [...html.matchAll(/data-view="([^"]+)"/g)].map(m => m[1]);
assert(JSON.stringify(views) === JSON.stringify(['fabricantes','integradores','mayoristas','tendencias','arquitecturas']), 'La navegación principal debe contener exactamente cinco áreas');
assert(html.includes('assets/v370/intelligence.js'), 'Falta JS v3.7');
assert(html.includes('assets/v370/intelligence.css'), 'Falta CSS v3.7');
assert(!html.includes('manufacturerRole'), 'Fabricantes no debe tener filtro de filas externas');
assert(js.includes("data/v37/intelligence.json"), 'El frontend no carga el dataset v3.7');
assert(js.includes('activeColumns'), 'Falta ocultación dinámica de columnas sin datos');
assert(js.includes('trace-popover'), 'Falta popover de trazabilidad por dato');
assert(js.includes('confidence-tag') && js.includes('confidence_band'), 'Faltan etiquetas por confianza');
assert(js.includes('data-more-tags'), 'Falta plegado de celdas largas');
assert(js.includes('toggleSort') && js.includes('reorderColumn'), 'Falta ordenar/reordenar columnas');
assert(js.includes('renderTrendAnalytics'), 'Faltan visualizaciones de tendencias');
assert(js.includes('help-icon'), 'Falta ayuda ? en cabeceras ambiguas');
assert(js.includes('westcon-font-scale'), 'Falta persistencia del tamaño de texto');
assert(html.includes('textLarger') && html.includes('textSmaller'), 'Faltan controles de tamaño de texto');
assert(data.manufacturers.length === 36, 'Fabricantes debe publicar exactamente el portfolio Westcon');
for (const section of ['manufacturers','integrators','distributors','trends','architectures']) assert(Array.isArray(data[section]) && data[section].length > 0, `Sin datos en ${section}`);
assert(js.includes('pptAddEntityCard') && js.includes('pptAddDetailCard'), 'El PPT no usa el sistema visual de tarjetas');
assert(js.includes('reportCover') && js.includes('r-intel-card'), 'El PDF no usa el sistema visual alineado con la web');
console.log('UI smoke v3.7.0 · PASS');
